# Question 3

In [1]:
import numpy as np
from numpy import c_

## 3.a)

In [2]:
# create the matrix M:
M = np.matrix([[0.4, 0.5, 0.2, 0.0],
               [0.3, 0.0, 0.4, 0.0],
               [0.3, 0.0, 0.4, 0.0],
               [0.0, 0.5, 0.0, 1.0]])
M

matrix([[0.4, 0.5, 0.2, 0. ],
        [0.3, 0. , 0.4, 0. ],
        [0.3, 0. , 0.4, 0. ],
        [0. , 0.5, 0. , 1. ]])

## 3.b)

In [3]:
# At t0 100mg at A and 200mg at B
t0 = np.matrix([[100], [200], [0], [0]])
t0

matrix([[100],
        [200],
        [  0],
        [  0]])

In [4]:
M*t0

matrix([[140.],
        [ 30.],
        [ 30.],
        [100.]])

In [5]:
# Patient is measured every 5 mins. t=10 mins means 2 simulations
M ** 2  * t0

matrix([[ 77.],
        [ 54.],
        [ 54.],
        [115.]])

In [6]:
# Patient is measured every 5 mins. t=20 mins means 4 simulations
M ** 4  * t0

matrix([[ 58.73],
        [ 38.46],
        [ 38.46],
        [164.35]])

##  3.c)

In [7]:
# Patient is measured every 5 mins. After 4 hours, t=240 mins means 48 simulations
M ** 48  * t0

matrix([[7.04863641e-02],
        [4.61441570e-02],
        [4.61441570e-02],
        [2.99837225e+02]])

## All together

In [8]:
#  The initial state of the system:
t0 = np.matrix([[100], [200], [0], [0]])

#Make a matrix, where each column is the result 
#of applying the matrix multiple times to the initial state x0:

X = np.c_[t0, M*t0, M**2 * t0, M**4 * t0, M**48 * t0]

#print out the X matrix, rounding the entries to 2 decimal places
print(X.round(2))


[[1.0000e+02 1.4000e+02 7.7000e+01 5.8730e+01 7.0000e-02]
 [2.0000e+02 3.0000e+01 5.4000e+01 3.8460e+01 5.0000e-02]
 [0.0000e+00 3.0000e+01 5.4000e+01 3.8460e+01 5.0000e-02]
 [0.0000e+00 1.0000e+02 1.1500e+02 1.6435e+02 2.9984e+02]]


## 3.d)

In [9]:
# find the determinant of the matrix
det = np.linalg.det(M)

# check if the matrix is invertible
if det == 0:
    print("Inverse does not exist")
else:
    # find the inverse of the matrix
    A_inv = np.linalg.inv(M)
    print(A_inv)

Inverse does not exist
